### ISSUE TITLE
在初始化模型的时候怎么选择CPU运行模式下的模型 ？

### ISSUE THREAD

**Issue by answerMA** [fastnlp/fastHan#41]
在头一次初始化后，程序自动下载模型，但是在使用时缺提示没有CUDA 不能load模型。

所以像请问在哪可以直接下载CPU的模型 或者有什么设置吗 

    134     if not torch.cuda.is_available():
--> 135         raise RuntimeError('Attempting to deserialize object on a CUDA '
    136                            'device but torch.cuda.is_available() is False. '
    137                            'If you are running on a CPU-only machine, '

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by zhichao-aws** [comment]
你的版本是1.*还是2.0呢？

**Comment by Jihuai-wpy** [comment]
你直接使用应该就可以吧，默认就是set cpu的。或者你可以邮箱联系我给我看一下你的报错信息吗

**Comment by Jihuai-wpy** [comment]
我大概想了下你的问题应该是这个吧，就是，目前你只是在加载模型嘛，所以跟你讲的选择没啥关系（而且其实模型不分模式，参数都同一个）。https://blog.csdn.net/weixin_42042072/article/details/125801302。 你尝试参考一下，应该是你的torch安装的不太对

**Comment by answerMA** [comment]
![image](https://user-images.githubusercontent.com/3457139/221110235-3d49e792-af58-4705-adea-2f46e343a5eb.png)

是这样的 也就是它在初始化的时候，是去自动下载相应的模型文件。
下载之后装载的时候就报 cuda false的错误 
![image](https://user-images.githubusercontent.com/3457139/221110396-267b467b-9793-47d0-9f3b-61ed0f84325a.png)

因为我的机器是CPU环境，它下载的这个模型文件我也没法通过初始化里的参数来修改成CPU环境的相应的文件 
而初始化不成功，也就无法通过 set方法转化成CPU环境的文件了 

请问这种情况有什么办法吗  

或者是我找到那个模型文件的路径，我在GPU的环境里自己转化一下 ？

**Comment by Jihuai-wpy** [comment]
我们这个模型默认都是使用cpu环境，只有你专门设置了才能使用gpu环境，你的报错信息少了中间的部分，但整体上跟我上一条发给你的链接非常相关。所以感觉应该是你cuda版本跟torch版本之间不匹配的问题。

**Comment by pantsing** [comment]
环境：
pytorch                   1.12.1          cpu_py310h64f2f56_1  

异常位置：
FastModel.py:164

解决方式：
torch.load() 添加参数 map_location=torch.device(self.device)

代码示例： 
`
self.model.load_state_dict(torch.load(model_path, map_location=torch.device(self.device)))
`

**Comment by Jihuai-wpy** [comment]
应该是这个问题，可能以前我从来没有注意过这个地方，直接加载是按照上次保存的map_location加载，所以使用cpu时需要重定向，我下一版会进行修改。感谢评论~

**Comment by finch-f** [comment]
我也遇到了这个问题，在mac上两台机器都试了，包括重新安装torch，还是会出现这个问题

**Comment by Jihuai-wpy** [comment]
你按照这个方法试过了吗



解决方式：
torch.load() 添加参数 map_location=torch.device(self.device)

代码示例：
self.model.load_state_dict(torch.load(model_path, map_location=torch.device(self.device)))





暮曦
***@***.***







                       
原始邮件
                       
                     

发件人："finch"< ***@***.*** &gt;;

发件时间：2023/4/28 17:42

收件人："fastnlp/fastHan"< ***@***.*** &gt;;

抄送人："Jihuai"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [fastnlp/fastHan] 在初始化模型的时候怎么选择CPU运行模式下的模型 ？ (Issue #41)




 
我也遇到了这个问题，在mac上两台机器都试了，包括重新安装torch，还是会出现这个问题

**Comment by finch-f** [comment]
> 

不太了解具体的操作方法。是需要到torch的源代码里修改这个位置的参数吗？

**Comment by 931902655** [comment]
2.0会有这个问题，我换成1.x的版本就好了
